name: dpug-dev
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - jupyter=1.0.0

  # Jupyter set up
  - ipykernel=6.4.1
  - nbconvert=5.6.1
  - notebook=6.4.4
  - jupyterlab=3.2.0

  ## Developer packages, packages below this comment will be ignored when
  # generating 'environment.yml' (see scripts/generate_env_from_dev.py)
  # for participant envrironment
  
  # jupyterlab plugins
  - jupyterlab-git
  - jupyterlab-spellchecker
  - jupytext=1.13.0

  # pin jupyter client
  - jupyter_client=6.1.12

  # sphinx tools
  - pydata-sphinx-theme=0.6.3
  - pandoc=2.14.2
  - pyyaml=5.4.1

  # sphinx extensions
  - myst-nb=0.13.0
  - sphinx-panels=0.6.0
  - sphinx-copybutton=0.4.0
  - sphinx-external-toc=0.2.3
  - sphinx-togglebutton=0.2.3

  # Code maintenance
  - black=21.9b0
  - flake8
  - pre-commit>=2.9.2
